name: "Draft new release"

on:
  issues:
    types: [opened, labeled]

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    # Only run for issues with a specific title and label. Not strictly required but makes finding the release issue again later easier.
    # There is also a whitelist that you may want to use to restrict, who can trigger this workflow.
    # Unfortunately, we cannot create an array on the fly, so the whitelist is just comma-separated.
    if: github.event.issue.state == 'open' && startsWith(github.event.issue.title, 'Release') && contains(github.event.issue.labels.*.name, 'release') && contains('imsteev', github.event.issue.user.login)
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Extract version from issue title
        run: |
          TITLE="${{ github.event.issue.title }}"
          VERSION=${TITLE#Release version }

          echo "::set-env name=RELEASE_VERSION::$VERSION"

      - name: Create release branch
        run: |
          git pull origin dev
          git checkout -b release
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
          git push origin release

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release
          base: master
          token: ${{ secrets.ACTIONS_TOKEN }}
          commit-message: Automated release PR 
          team-reviewers: team
          title: ${{ github.event.issue.title }}
          reviewers: ${{ github.event.issue.user.login }} # By default, we request a review from the person who opened the issue. You can replace this with a static list of users.
          # Write a nice message to the user.
          # We are claiming things here based on the `publish-new-release.yml` workflow.
          # You should obviously adopt it to say the truth depending on your release workflow :)
          body: |
            Fixes #${{ github.event.issue.number }}

            ##### _Created by @${{ github.event.issue.user.login }}_
